version: '3.1'
services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
    networks:
      default:
        ipv4_address: 172.18.0.200
    expose:
      - 3306
    volumes:
      - mysql:/var/lib/mysql
  mongo:
    image: mongo
    restart: always
    networks:
      default:
        ipv4_address: 172.18.0.203
    volumes:
      - mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  mongo-express:
    image: mongo-express
    restart: always
    networks:
      default:
        ipv4_address: 172.18.0.204
    expose:
      - 8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
  redis:
    image: redis
    restart: always
    networks: 
      default:
        ipv4_address: 172.18.0.202
    expose:
      - 6379
  adminer:
    image: adminer
    restart: always
    networks:
      default:
        ipv4_address: 172.18.0.201
    expose:
      - 8080
    links:
      - mysql:db
  passport:
    build: LNEnvios-PASSPORT
    networks:
      default:
        ipv4_address: 172.18.0.2
        aliases:
          - lne-passport.vm
    ports:
      - 80
      - 443
    environment:
      - WEB_DOCUMENT_ROOT=/app/public
      - WEB_ALIAS_DOMAIN=lne-passport.vm
    volumes:
      - c:/code/hop/LNEnvios-PASSPORT/:/app/
  api:
    build: LNEnvios-API
    networks:
      default:
        ipv4_address: 172.18.0.3
        aliases:
          - lne-api.vm
    ports:
      - 80
      - 443
    environment:
      - WEB_DOCUMENT_ROOT=/app/public
      - WEB_ALIAS_DOMAIN=lne-api.vm
    volumes:
      - c:/code/hop/LNEnvios-API/:/app/
  got:
    build: LNEnvios-GOT
    networks:
      default:
        ipv4_address: 172.18.0.4
        aliases:
          - lne-got.vm
    ports:
      - 80
      - 443
    environment:
      - WEB_DOCUMENT_ROOT=/app/public
      - WEB_ALIAS_DOMAIN=lne-got.vm
    volumes:
      - c:/code/hop/LNEnvios-GOT/:/app/
  gpde:
    build: LNEnvios-GPDE
    networks:
      default:
        ipv4_address: 172.18.0.5
        aliases:
          - lne-gpde.vm
    ports:
      - 80
      - 443
    environment:
      - WEB_DOCUMENT_ROOT=/app/public
      - WEB_ALIAS_DOMAIN=lne-gpde.vm
      - XDEBUG_REMOTE_AUTOSTART=1
    volumes:
      - c:/code/hop/LNEnvios-GPDE/:/app/
  gpde-phpunit:
    build: LNEnvios-GPDE
    environment:
      - WEB_DOCUMENT_ROOT=/app/public
      - WEB_ALIAS_DOMAIN=lne-gpde.vm
      - XDEBUG_REMOTE_AUTOSTART=1
    volumes:
      - c:/code/hop/LNEnvios-GPDE/:/app/
  gven:
    build: LNEnvios-GVEN
    networks:
      default:
        ipv4_address: 172.18.0.6
        aliases:
          - lne-gven.vm
    ports:
      - 80
      - 443
    environment:
      - WEB_DOCUMENT_ROOT=/app/public
      - WEB_ALIAS_DOMAIN=lne-gven.vm
    volumes:
      - c:/code/hop/LNEnvios-GVEN/:/app/
  notificaciones:
    build: LNEnvios-NOTIFICACIONES
    networks:
      default:
        ipv4_address: 172.18.0.7
        aliases:
          - lne-notificaciones.vm
    ports:
      - 80
      - 443
    environment:
      - WEB_DOCUMENT_ROOT=/app/public
      - WEB_ALIAS_DOMAIN=lne-notificaciones.vm
    volumes:
      - c:/code/hop/LNEnvios-NOTIFICACIONES/:/app/
  queue:
    build: LNEnvios-QUEUE
    networks:
      default:
        ipv4_address: 172.18.0.8
        aliases:
          - lne-queue.vm
    ports:
      - 80
      - 443
    environment:
      - WEB_DOCUMENT_ROOT=/app/public
      - WEB_ALIAS_DOMAIN=lne-queue.vm
    volumes:
      - c:/code/hop/LNEnvios-QUEUE/:/app/
  mime:
    build: LNEnvios-MIME
    networks:
      default:
        ipv4_address: 172.18.0.9
        aliases:
          - lne-mime.vm
    ports:
      - 80
      - 443
    environment:
      - WEB_DOCUMENT_ROOT=/app/public
      - WEB_ALIAS_DOMAIN=lne-mime.vm
    volumes:
      - c:/code/hop/LNEnvios-MIME/:/app/
networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16
volumes:
  mongo:
    driver: local
  mysql:
    driver: local
