version: '3'
services:
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
    networks:
      default:
        ipv4_address: 172.18.0.200
    expose:
      - 3306
    volumes:
      - $HOME/code/hop/mysql/:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
     - PMA_ARBITRARY=1
     - PMA_HOST=172.18.0.200
     - MYSQL_ROOT_PASSWORD=secret
     - PMA_ABSOLUTE_URI=http://lne-phpmyadmin.vm
    restart: always
    expose:
     - 80
    networks:
      default:
        ipv4_address: 172.18.0.201
        aliases:
          - lne-phpmyadmin.vm
    volumes:
     - /sessions
  passport:
    image: webdevops/php-nginx:7.0
    restart: always
    networks:
      default:
        ipv4_address: 172.18.0.2
        aliases:
          - lne-passport.vm
    expose:
      - 80
      - 443
    environment:
      - WEB_DOCUMENT_ROOT=/app/public
      - WEB_ALIAS_DOMAIN=lne-passport.vm
    volumes:
      - $HOME/code/hop/LNEnvios-PASSPORT/:/app/
  api:
    image: webdevops/php-nginx:7.0
    restart: always
    networks:
      default:
        ipv4_address: 172.18.0.3
        aliases:
          - lne-api.vm
    expose:
      - 80
      - 443
    environment:
      - WEB_DOCUMENT_ROOT=/app/public
      - WEB_ALIAS_DOMAIN=lne-api.vm
    volumes:
      - $HOME/code/hop/LNEnvios-API/:/app/
  got:
    image: webdevops/php-nginx:7.0
    restart: always
    networks:
      default:
        ipv4_address: 172.18.0.4
        aliases:
          - lne-got.vm
    ports:
      - 80
      - 443
    environment:
      - WEB_DOCUMENT_ROOT=/app/public
      - WEB_ALIAS_DOMAIN=lne-got.vm
    volumes:
      - $HOME/code/hop/LNEnvios-GOT/:/app/
  gpde:
    image: webdevops/php-nginx:7.0
    restart: always
    networks:
      default:
        ipv4_address: 172.18.0.5
        aliases:
          - lne-gpde.vm
    expose:
      - 80
      - 443
    environment:
      - WEB_DOCUMENT_ROOT=/app/public
      - WEB_ALIAS_DOMAIN=lne-gpde.vm
    volumes:
      - $HOME/code/hop/LNEnvios-GPDE/:/app/
  gven:
    image: webdevops/php-nginx:7.0
    restart: always
    networks:
      default:
        ipv4_address: 172.18.0.6
        aliases:
          - lne-gven.vm
    expose:
      - 80
      - 443
    environment:
      - WEB_DOCUMENT_ROOT=/app/public
      - WEB_ALIAS_DOMAIN=lne-gven.vm
    volumes:
      - $HOME/code/hop/LNEnvios-GVEN/:/app/
  notificaciones:
    image: webdevops/php-nginx:7.0
    restart: always
    networks:
      default:
        ipv4_address: 172.18.0.7
        aliases:
          - lne-notificaciones.vm
    expose:
      - 80
      - 443
    environment:
      - WEB_DOCUMENT_ROOT=/app/public
      - WEB_ALIAS_DOMAIN=lne-notificaciones.vm
    volumes:
      - $HOME/code/hop/LNEnvios-NOTIFICACIONES/:/app/
  queue:
    image: webdevops/php-nginx:7.0
    restart: always
    networks:
      default:
        ipv4_address: 172.18.0.8
        aliases:
          - lne-queue.vm
    expose:
      - 80
      - 443
    environment:
      - WEB_DOCUMENT_ROOT=/app/public
      - WEB_ALIAS_DOMAIN=lne-queue.vm
    volumes:
      - $HOME/code/hop/LNEnvios-QUEUE/:/app/
networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16
